services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXTCLOUD_WEBDAV_URL=${NEXTCLOUD_WEBDAV_URL}
      - NEXTCLOUD_USERNAME=${NEXTCLOUD_USERNAME}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
      - PORT=3000
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped